services:
  spring-api-image:
    image: spring-api
    container_name: spring-api-container
    ##Automatiza la construcción de la imagen
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - spring-network

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: 1998
      MYSQL_DATABASE: dockerDB
      MYSQL_USER: ysimijaca
      MYSQL_PASSWORD: toor
    ports:
      - "3308:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql
networks:
  spring-network:
volumes:
  mysql-volume:

